// Generated by `pnpm dither`. Do not edit by hand.
export type DitherName =
  | 'pigmo'
  | 'zeus-agrotech'
  | 'redux-store'
  | 'pepy-the-platypus'
  | 'equals-venue'
  | 'equals-sport'
  | 'equals9'
  | 'portrait'

export type DitherAsset = {
  png: string
  webp: string
  width: number
  height: number
  cssWidth: number
  cssHeight: number
}

export const dithered: Record<DitherName, DitherAsset> = {
  pigmo: {
    png: '/dither/pigmo.png',
    webp: '/dither/pigmo.webp',
    width: 1828,
    height: 2260,
    cssWidth: 914,
    cssHeight: 1130,
  },
  'zeus-agrotech': {
    png: '/dither/zeus-agrotech.png',
    webp: '/dither/zeus-agrotech.webp',
    width: 914,
    height: 1130,
    cssWidth: 457,
    cssHeight: 565,
  },
  'redux-store': {
    png: '/dither/redux-store.png',
    webp: '/dither/redux-store.webp',
    width: 1828,
    height: 2260,
    cssWidth: 914,
    cssHeight: 1130,
  },
  'pepy-the-platypus': {
    png: '/dither/pepy-the-platypus.png',
    webp: '/dither/pepy-the-platypus.webp',
    width: 914,
    height: 1130,
    cssWidth: 457,
    cssHeight: 565,
  },
  'equals-venue': {
    png: '/dither/equals-venue.png',
    webp: '/dither/equals-venue.webp',
    width: 914,
    height: 1130,
    cssWidth: 457,
    cssHeight: 565,
  },
  'equals-sport': {
    png: '/dither/equals-sport.png',
    webp: '/dither/equals-sport.webp',
    width: 914,
    height: 1130,
    cssWidth: 457,
    cssHeight: 565,
  },
  equals9: {
    png: '/dither/equals9.png',
    webp: '/dither/equals9.webp',
    width: 914,
    height: 1130,
    cssWidth: 457,
    cssHeight: 565,
  },
  portrait: {
    png: '/dither/portrait.png',
    webp: '/dither/portrait.webp',
    width: 1704,
    height: 1984,
    cssWidth: 852,
    cssHeight: 992,
  },
}
