// Generated by `pnpm dither`. Do not edit by hand.
export type SceneName =
  | 'home-paladin'
  | 'about-paladin'
  | 'avatar'
  | 'projects-wall'
  | 'bookshelf-library'
  | 'notebook-desk'
  | 'tech-bench'
  | 'contact-letter'
  | 'bookshelf-empty'

export type SceneAsset = {
  png: string
  webp: string
  width: number
  height: number
  cssWidth: number
  cssHeight: number
}

export const scenes: Record<SceneName, SceneAsset> = {
  'home-paladin': {
    png: '/scenes/home-paladin.png',
    webp: '/scenes/home-paladin.webp',
    width: 2880,
    height: 3858,
    cssWidth: 1440,
    cssHeight: 1929,
  },
  'about-paladin': {
    png: '/scenes/about-paladin.png',
    webp: '/scenes/about-paladin.webp',
    width: 2880,
    height: 3908,
    cssWidth: 1440,
    cssHeight: 1954,
  },
  avatar: {
    png: '/scenes/avatar.png',
    webp: '/scenes/avatar.webp',
    width: 2880,
    height: 2880,
    cssWidth: 1440,
    cssHeight: 1440,
  },
  'projects-wall': {
    png: '/scenes/projects-wall.png',
    webp: '/scenes/projects-wall.webp',
    width: 2880,
    height: 1222,
    cssWidth: 1440,
    cssHeight: 611,
  },
  'bookshelf-library': {
    png: '/scenes/bookshelf-library.png',
    webp: '/scenes/bookshelf-library.webp',
    width: 2880,
    height: 1446,
    cssWidth: 1440,
    cssHeight: 723,
  },
  'notebook-desk': {
    png: '/scenes/notebook-desk.png',
    webp: '/scenes/notebook-desk.webp',
    width: 2880,
    height: 1222,
    cssWidth: 1440,
    cssHeight: 611,
  },
  'tech-bench': {
    png: '/scenes/tech-bench.png',
    webp: '/scenes/tech-bench.webp',
    width: 2880,
    height: 1136,
    cssWidth: 1440,
    cssHeight: 568,
  },
  'contact-letter': {
    png: '/scenes/contact-letter.png',
    webp: '/scenes/contact-letter.webp',
    width: 2880,
    height: 1608,
    cssWidth: 1440,
    cssHeight: 804,
  },
  'bookshelf-empty': {
    png: '/scenes/bookshelf-empty.png',
    webp: '/scenes/bookshelf-empty.webp',
    width: 2880,
    height: 1932,
    cssWidth: 1440,
    cssHeight: 966,
  },
}
