import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { Algorithm, CELL } from './dither/core'
import { scenes } from './dither/manifest'
import { renderScene } from './dither/pipeline'

const ROOT = process.cwd()
const OUT_DIR = path.join(ROOT, 'public', 'scenes')
const GENERATED = path.join(ROOT, 'src', 'configs', 'scenes.generated.ts')

type Rendered = { name: string; width: number; height: number }

async function writeOutputs(
  base: string,
  algorithm: Algorithm,
  source: string
): Promise<{ width: number; height: number }> {
  const out = await renderScene(source, algorithm)
  await mkdir(path.dirname(base), { recursive: true })
  await writeFile(`${base}.png`, out.png)
  await writeFile(`${base}.webp`, out.webp)
  console.log(
    `${path.relative(ROOT, base)}  ${out.width}×${out.height}  (${algorithm}, png ${Math.round(out.png.length / 1024)} KB, webp ${Math.round(out.webp.length / 1024)} KB)`
  )
  return { width: out.width, height: out.height }
}

function generatedSource(list: Rendered[]): string {
  const names = list.map((s) => `'${s.name}'`).join(' | ')
  const entries = list
    .map(
      (s) => `  '${s.name}': {
    png: '/scenes/${s.name}.png',
    webp: '/scenes/${s.name}.webp',
    width: ${s.width},
    height: ${s.height},
    cssWidth: ${s.width / CELL},
    cssHeight: ${s.height / CELL},
  },`
    )
    .join('\n')
  return `// Generated by \`pnpm dither\`. Do not edit by hand.
export type SceneName = ${names}

export type SceneAsset = {
  png: string
  webp: string
  width: number
  height: number
  cssWidth: number
  cssHeight: number
}

export const scenes: Record<SceneName, SceneAsset> = {
${entries}
}
`
}

async function runManifest() {
  const rendered: Rendered[] = []
  for (const scene of scenes) {
    const source = path.join(ROOT, scene.source)
    if (!existsSync(source)) {
      console.warn(`skip ${scene.name}: missing ${scene.source}`)
      continue
    }
    const dims = await writeOutputs(
      path.join(OUT_DIR, scene.name),
      scene.algorithm,
      source
    )
    rendered.push({ name: scene.name, ...dims })
  }
  if (rendered.length === 0) {
    console.error('no scenes rendered — add sources under art/source/')
    process.exit(1)
  }
  await writeFile(GENERATED, generatedSource(rendered))
  console.log(`wrote ${path.relative(ROOT, GENERATED)}`)
}

async function runAdHoc(input: string, outputBase: string, algorithm: string) {
  if (algorithm !== 'bayer' && algorithm !== 'floyd-steinberg') {
    console.error(`unknown algorithm "${algorithm}"`)
    process.exit(1)
  }
  await writeOutputs(path.resolve(outputBase), algorithm, path.resolve(input))
}

const [, , input, outputBase, algorithm = 'bayer'] = process.argv
if (input && outputBase) {
  runAdHoc(input, outputBase, algorithm)
} else {
  runManifest()
}
