import { existsSync } from 'node:fs'
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { CELL } from './dither/core'
import type { Algorithm } from './dither/core'
import { dithered, scenes } from './dither/manifest'
import { renderScene } from './dither/pipeline'

const ROOT = process.cwd()
const OUT_DIR = path.join(ROOT, 'public', 'scenes')
const GENERATED = path.join(ROOT, 'src', 'configs', 'scenes.generated.ts')
const DITHER_DIR = path.join(ROOT, 'public', 'dither')
const DITHER_GENERATED = path.join(
  ROOT,
  'src',
  'configs',
  'dither.generated.ts'
)

type Rendered = { name: string; width: number; height: number }

async function writeOutputs(
  base: string,
  algorithm: Algorithm,
  source: string
): Promise<{ width: number; height: number }> {
  const out = await renderScene(source, algorithm)
  await mkdir(path.dirname(base), { recursive: true })
  await writeFile(`${base}.png`, out.png)
  await writeFile(`${base}.webp`, out.webp)
  console.log(
    `${path.relative(ROOT, base)}  ${out.width}×${out.height}  (${algorithm}, png ${Math.round(out.png.length / 1024)} KB, webp ${Math.round(out.webp.length / 1024)} KB)`
  )
  return { width: out.width, height: out.height }
}

type GeneratedSourceOptions = {
  typeName: string
  assetType: string
  exportName: string
  dir: string
}

function generatedSource(
  list: Rendered[],
  { typeName, assetType, exportName, dir }: GeneratedSourceOptions
): string {
  const names = list.map((s) => `'${s.name}'`).join(' | ')
  const entries = list
    .map(
      (s) => `  '${s.name}': {
    png: '${dir}/${s.name}.png',
    webp: '${dir}/${s.name}.webp',
    width: ${s.width},
    height: ${s.height},
    cssWidth: ${s.width / CELL},
    cssHeight: ${s.height / CELL},
  },`
    )
    .join('\n')
  return `// Generated by \`pnpm dither\`. Do not edit by hand.
export type ${typeName} = ${names}

export type ${assetType} = {
  png: string
  webp: string
  width: number
  height: number
  cssWidth: number
  cssHeight: number
}

export const ${exportName}: Record<${typeName}, ${assetType}> = {
${entries}
}
`
}

async function runManifest() {
  const rendered: Rendered[] = []
  for (const scene of scenes) {
    const source = path.join(ROOT, scene.source)
    if (!existsSync(source)) {
      console.warn(`skip ${scene.name}: missing ${scene.source}`)
      continue
    }
    const dims = await writeOutputs(
      path.join(OUT_DIR, scene.name),
      scene.algorithm,
      source
    )
    rendered.push({ name: scene.name, ...dims })
  }
  if (rendered.length === 0) {
    console.error('no scenes rendered — add sources under art/source/')
    process.exit(1)
  }
  await writeFile(
    GENERATED,
    generatedSource(rendered, {
      typeName: 'SceneName',
      assetType: 'SceneAsset',
      exportName: 'scenes',
      dir: '/scenes',
    })
  )
  console.log(`wrote ${path.relative(ROOT, GENERATED)}`)

  await mkdir(DITHER_DIR, { recursive: true })
  const renderedDither: Rendered[] = []
  for (const entry of dithered) {
    const source = path.join(ROOT, entry.source)
    if (!existsSync(source)) {
      console.warn(`skip ${entry.name}: missing ${entry.source}`)
      continue
    }
    const dims = await writeOutputs(
      path.join(DITHER_DIR, entry.name),
      entry.algorithm,
      source
    )
    renderedDither.push({ name: entry.name, ...dims })
  }
  await writeFile(
    DITHER_GENERATED,
    generatedSource(renderedDither, {
      typeName: 'DitherName',
      assetType: 'DitherAsset',
      exportName: 'dithered',
      dir: '/dither',
    })
  )
  console.log(`wrote ${path.relative(ROOT, DITHER_GENERATED)}`)
}

async function runAdHoc(input: string, outputBase: string, algorithm: string) {
  if (algorithm !== 'bayer' && algorithm !== 'floyd-steinberg') {
    console.error(`unknown algorithm "${algorithm}"`)
    process.exit(1)
  }
  await writeOutputs(path.resolve(outputBase), algorithm, path.resolve(input))
}

async function run() {
  const [, , input, outputBase, algorithm = 'bayer'] = process.argv
  if (input && !outputBase) {
    console.error(
      'usage: pnpm dither [<input> <outputBase> [bayer|floyd-steinberg]]'
    )
    process.exit(1)
  }
  if (input && outputBase) {
    await runAdHoc(input, outputBase, algorithm)
  } else {
    await runManifest()
  }
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
