import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import sharp from 'sharp'
import { Potrace, PotraceOptions } from 'potrace'

const REPO_ROOT = path.resolve(__dirname, '..')
const MAX_DIMENSION = 800
const PADDING_RATIO = 0.04

const DEFAULT_POTRACE_OPTIONS: PotraceOptions = {
  threshold: 128,
  blackOnWhite: false,
  turdSize: 24,
  optTolerance: 0.4,
  alphaMax: 1,
}

async function preprocess(inputPath: string, square: boolean) {
  const resized = await sharp(inputPath)
    .resize({
      width: MAX_DIMENSION,
      height: MAX_DIMENSION,
      fit: 'inside',
    })
    .toBuffer()

  const { data: trimmed, info: trimmedInfo } = await sharp(resized)
    .trim()
    .toBuffer({ resolveWithObject: true })

  const { width: tw, height: th } = trimmedInfo

  let left: number, right: number, top: number, bottom: number
  let width: number, height: number

  if (square) {
    const side = Math.max(tw, th)
    const pad = Math.round(side * PADDING_RATIO)
    width = height = side + pad * 2
    left = Math.floor((width - tw) / 2)
    right = width - tw - left
    top = Math.floor((height - th) / 2)
    bottom = height - th - top
  } else {
    const padX = Math.round(tw * PADDING_RATIO)
    const padY = Math.round(th * PADDING_RATIO)
    left = right = padX
    top = bottom = padY
    width = tw + padX * 2
    height = th + padY * 2
  }

  const buffer = await sharp(trimmed)
    .extend({
      top,
      bottom,
      left,
      right,
      background: { r: 0, g: 0, b: 0, alpha: 1 },
    })
    .grayscale()
    .threshold(128)
    .png()
    .toBuffer()

  return { buffer, width, height }
}

function vectorize(buffer: Buffer, options: PotraceOptions): Promise<string> {
  return new Promise((resolve, reject) => {
    const trace = new Potrace(options)
    trace.loadImage(buffer, function (this: Potrace, err: Error | null) {
      if (err) {
        reject(err)
        return
      }
      const tag = this.getPathTag()
      const match = tag.match(/d="([^"]+)"/)
      if (!match) {
        reject(new Error('potrace produced a path tag with no d attribute'))
        return
      }
      resolve(match[1])
    })
  })
}

async function trace(
  name: string,
  inputPath: string,
  square: boolean,
  options: PotraceOptions
) {
  const { buffer, width, height } = await preprocess(inputPath, square)
  const d = await vectorize(buffer, options)
  const kb = (Buffer.byteLength(d) / 1024).toFixed(1)
  console.log(`${name}: viewBox 0 0 ${width} ${height}, d = ${kb} KB`)
  return { viewBox: `0 0 ${width} ${height}`, d }
}

async function run() {
  const nohalo = await trace(
    'FM_PLAIN',
    path.join(REPO_ROOT, 'art/mark/fm-nohalo.png'),
    false,
    DEFAULT_POTRACE_OPTIONS
  )

  let halo = await trace(
    'FM_HALO',
    path.join(REPO_ROOT, 'art/mark/fm-halo.png'),
    true,
    DEFAULT_POTRACE_OPTIONS
  )

  const haloKb = Buffer.byteLength(halo.d) / 1024
  if (haloKb > 150) {
    console.log(
      `FM_HALO exceeded 150 KB (${haloKb.toFixed(1)} KB), retracing with looser tolerance`
    )
    halo = await trace(
      'FM_HALO',
      path.join(REPO_ROOT, 'art/mark/fm-halo.png'),
      true,
      { ...DEFAULT_POTRACE_OPTIONS, turdSize: 40, optTolerance: 0.8 }
    )
  }

  const outPath = path.join(
    REPO_ROOT,
    'src/assets/ex-libris/monogram.generated.ts'
  )

  const contents = `// Generated by \`pnpm vectorize\`. Do not edit by hand.
export type Monogram = { viewBox: string; d: string }

export const FM_HALO: Monogram = ${JSON.stringify(halo, null, 2)}

export const FM_PLAIN: Monogram = ${JSON.stringify(nohalo, null, 2)}
`

  await mkdir(path.dirname(outPath), { recursive: true })
  await writeFile(outPath, contents)
  console.log(`wrote ${path.relative(REPO_ROOT, outPath)}`)
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
